version: '3.8'

services:
  db2:
    image: ibmcom/db2
    container_name: contenedor-db2
    ports:
      - "50000:50000"
    environment:
      DB2INST1_PASSWORD: db2pass
      LICENSE: accept
    privileged: true
    volumes:
      - ./data/db2:/database
    restart: always

  backend:
    build: ./backend-elecciones
    container_name: contenedor-backend
    ports:
      - "3001:3001"
    depends_on:
      - db2
    environment:
      DB_NAME: VOTACION
      DB_USER: db2inst1
      DB_PASSWORD: db2pass
      DB_HOST: db2
      DB_PORT: 50000
    restart: always

  frontend:
    build: ./frontend-elecciones
    container_name: contenedor-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: always
