version: '3.8'

services:
  db2:
    image: ibmcom/db2
    container_name: contenedor-db2
    ports:
      - "50000:50000"
    environment:
      DB2INST1_PASSWORD: db2pass
      LICENSE: accept
    privileged: true
    volumes:
      - ./data/db2:/database
    restart: always

